const categories={Movies:['🎬','purple'],Content:['▶️','red'],Instagram:['◎','pink'],Personal:['⌂','blue'],Health:['✦','green'],'Game Dev':['🎮','amber'],Work:['▣','cyan']};
const repeatOptions=['Never','Daily','Weekly','Alternate days','Weekdays','Monthly','Smart check'];
const alertOptions=[['At time',0],['10 min before',10],['15 min before',15],['30 min before',30],['1 hour before',60],['1 day before',1440]];
const starter=[
{id:'r1',title:'Daily movie recommendation',category:'Content',type:'routine',priority:'important',due:todayAt(19),repeat:'Daily',alertOffset:15,notes:'Pick movie → verify OTT India → prepare clip → caption.',done:false},
{id:'r2',title:'Telugu release tracker',category:'Movies',type:'smart',priority:'important',due:addDays(new Date(),1).toISOString(),repeat:'Smart check',alertOffset:0,notes:'Reconfirm release date from reliable sources before notifying.',done:false},
{id:'r3',title:'Frame of Today',category:'Instagram',type:'routine',priority:'normal',due:todayAt(20),repeat:'Alternate days',alertOffset:15,notes:'Choose cinematic frame set and finish colour composition.',done:false},
{id:'r4',title:'Game development practice',category:'Game Dev',type:'reminder',priority:'normal',due:addDays(new Date(),2).toISOString(),repeat:'Weekly',alertOffset:30,notes:'Unity + Blender learning session with one small playable outcome.',done:false}
];
function todayAt(h){const d=new Date();d.setHours(h,0,0,0);return d.toISOString()}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function endOfDay(d=new Date()){const x=new Date(d);x.setHours(23,59,59,999);return x}
function loadJSON(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback}catch{return fallback}}
let reminders=loadJSON('pulse.reminders',starter).map(r=>({...r,alertOffset:r.alertOffset??0}));
let history=loadJSON('pulse.history',[]);
let state={tab:'today',filter:'All',query:'',dark:localStorage.getItem('pulse.theme')!=='light',modal:null,snoozeId:null,toast:''};
function save(){localStorage.setItem('pulse.reminders',JSON.stringify(reminders));localStorage.setItem('pulse.history',JSON.stringify(history))}
function setTheme(dark){state.dark=dark;localStorage.setItem('pulse.theme',dark?'dark':'light');render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function localInputValue(iso){const d=new Date(iso);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function isToday(iso){const d=new Date(iso),n=new Date();return d.toDateString()===n.toDateString()}
function isOverdue(r){return !r.done&&new Date(r.due)<new Date()&&!isToday(r.due)}
function fmtDue(iso){const d=new Date(iso),n=new Date(),t=new Date();t.setDate(t.getDate()+1);let day=d.toDateString()===n.toDateString()?'Today':d.toDateString()===t.toDateString()?'Tomorrow':d.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});return day+' · '+d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}
function alertLabel(offset){return alertOptions.find(x=>x[1]===Number(offset))?.[0]||'At time'}
function tabTitle(){return {today:'Today',upcoming:'Upcoming',automations:'Automations',all:'All reminders',history:'History'}[state.tab]||'Today'}
function tabFiltered(items){const todayEnd=endOfDay();if(state.tab==='today')return items.filter(r=>!r.done&&new Date(r.due)<=todayEnd);if(state.tab==='upcoming')return items.filter(r=>!r.done&&new Date(r.due)>todayEnd);if(state.tab==='automations')return items.filter(r=>r.type==='smart'&&!r.done);if(state.tab==='all')return items;return items}
function visibleReminders(){return tabFiltered(reminders).filter(r=>state.filter==='All'||r.category===state.filter).filter(r=>(r.title+' '+r.notes+' '+r.category+' '+r.repeat).toLowerCase().includes(state.query.toLowerCase())).sort((a,b)=>Number(a.done)-Number(b.done)||new Date(a.due)-new Date(b.due))}
function showToast(message){state.toast=message;render();clearTimeout(showToast.t);showToast.t=setTimeout(()=>{state.toast='';render()},2200)}
function render(){document.documentElement.dataset.theme=state.dark?'dark':'light';const open=reminders.filter(r=>!r.done).length,smart=reminders.filter(r=>r.type==='smart'&&!r.done).length,doneToday=history.filter(h=>isToday(h.completedAt)).length,overdue=reminders.filter(isOverdue).length,visible=visibleReminders();
app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">⚡</div><div><span>Pulse</span><small>V2</small></div></div><nav>${nav('today','⌂','Today',reminders.filter(r=>!r.done&&new Date(r.due)<=endOfDay()).length)}${nav('upcoming','▦','Upcoming')}${nav('automations','✦','Automations',smart)}${nav('all','☷','All reminders',open)}${nav('history','↺','History')}</nav><div class="sidebar-spacer"></div><div class="sync-pill"><span class="status-dot"></span><div><b>Local mode</b><small>Cloud sync is next</small></div></div><button class="sidebar-action" onclick="requestNotifications()">🔔 ${notificationText()}</button><button class="sidebar-action" onclick="setTheme(!state.dark)">${state.dark?'☀️ Light mode':'🌙 Dark mode'}</button></aside><main class="main"><header class="topbar"><div><p class="eyebrow">PERSONAL COMMAND CENTER</p><h1>${tabTitle()}</h1><p class="page-subtitle">${state.tab==='today'?'Your active focus, ordered by time and urgency.':state.tab==='history'?'A lightweight log of what you completed.':'Plan, review and adjust what comes next.'}</p></div><div class="top-actions"><div class="search-box">⌕<input value="${esc(state.query)}" oninput="state.query=this.value;render()" placeholder="Search reminders"></div><button class="primary" onclick="openCreate()">＋ New reminder</button></div></header>${state.tab==='history'?historyView():dashboard(open,smart,doneToday,overdue,visible)} </main><nav class="mobile-nav">${nav('today','⌂','Today')}${nav('upcoming','▦','Upcoming')}<button class="mobile-add" onclick="openCreate()">＋</button>${nav('automations','✦','Smart')}${nav('all','☷','All')}</nav>${state.modal?modal():''}${state.snoozeId?snoozeSheet():''}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`}
function dashboard(open,smart,doneToday,overdue,visible){return `<section class="hero-grid"><button class="focus-card" onclick="state.tab='today';render()"><div class="focus-icon">✦</div><div><p class="muted">Focus for today</p><h2>${open===0?'You’re all clear.':open+' active reminders'}</h2><p class="muted small">${overdue?overdue+' overdue · ':''}${smart} smart checks active.</p></div><span class="chev">›</span></button><div class="stat-card"><span class="stat-label">Completed today</span><strong>${doneToday}</strong><span class="stat-foot">✓ logged</span></div><div class="stat-card"><span class="stat-label">Smart checks</span><strong>${smart}</strong><span class="stat-foot">⚡ active</span></div></section><section class="section-head"><div><p class="section-kicker">YOUR FLOW</p><h2>${state.tab==='today'?'What needs your attention':state.tab==='automations'?'Automations & smart checks':'Your reminders'}</h2></div><div class="chips">${['All',...Object.keys(categories)].map(c=>`<button class="chip ${state.filter===c?'active':''}" onclick="state.filter='${c}';render()">${c}</button>`).join('')}</div></section><section class="reminder-list">${visible.length?visible.map(card).join(''):`<div class="empty"><div>✓</div><h3>Nothing here</h3><p>${state.query?'No reminder matches your search.':'Try another filter or add a reminder.'}</p></div>`}</section><section class="automation-banner"><div class="automation-icon">✦</div><div><p class="section-kicker">V2 FOUNDATION</p><h3>Smart reminders now have a clearer home.</h3><p>Editing, recurrence, history and better scheduling work locally. Supabase, real push delivery and Calendar sync come in the connected layer.</p></div><button class="secondary" onclick="state.tab='automations';render()">View automations</button></section>`}
function historyView(){const items=[...history].sort((a,b)=>new Date(b.completedAt)-new Date(a.completedAt));return `<section class="history-head"><div><p class="section-kicker">COMPLETION LOG</p><h2>${items.length} completed actions</h2></div>${items.length?`<button class="secondary" onclick="clearHistory()">Clear history</button>`:''}</section><section class="history-list">${items.length?items.map(h=>`<article class="history-item"><div class="history-check">✓</div><div><h3>${esc(h.title)}</h3><p>${esc(h.category)} · ${new Date(h.completedAt).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</p></div><span>${esc(h.repeat||'Never')}</span></article>`).join(''):`<div class="empty"><div>↺</div><h3>No completion history yet</h3><p>Completed reminders will appear here.</p></div>`}</section>`}
function nav(id,icon,label,badge=''){return `<button class="nav-item ${state.tab===id?'active':''}" onclick="state.tab='${id}';state.filter='All';render()"><span class="nav-icon">${icon}</span><span>${label}</span>${badge?`<b>${badge}</b>`:''}</button>`}
function card(r){const [icon,cls]=categories[r.category]||categories.Personal,overdue=isOverdue(r);return `<article class="reminder-card ${r.done?'done':''} ${overdue?'overdue':''}"><button class="check" onclick="completeReminder('${r.id}')">${r.done?'✓':''}</button><div class="category-icon ${cls}">${icon}</div><div class="reminder-body"><div class="title-line"><h3>${esc(r.title)}</h3>${r.type==='smart'?'<span class="smart-tag">✦ Smart</span>':''}${r.priority==='important'?'<span class="priority-tag">🔥 Important</span>':''}${overdue?'<span class="overdue-tag">Overdue</span>':''}</div>${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="meta-row"><span>◷ ${fmtDue(r.due)}</span><span>↻ ${esc(r.repeat)}</span><span>🔔 ${alertLabel(r.alertOffset)}</span><span class="cat-dot ${cls}">${esc(r.category)}</span></div></div><div class="card-actions"><button title="Edit" onclick="openEdit('${r.id}')">✎</button>${!r.done?`<button title="Snooze" onclick="openSnooze('${r.id}')">◷</button>`:''}<button title="Delete" onclick="removeReminder('${r.id}')">⌫</button></div></article>`}
function openCreate(){state.modal={mode:'create'};render()}
function openEdit(id){state.modal={mode:'edit',id};render()}
function modal(){const editing=state.modal.mode==='edit',r=editing?reminders.find(x=>x.id===state.modal.id):null,due=r?.due||new Date(Date.now()+3600000).toISOString();return `<div class="modal-backdrop" onclick="closeModal()"><form class="modal" onclick="event.stopPropagation()" onsubmit="saveReminderForm(event)"><div class="modal-head"><div><p class="section-kicker">${editing?'EDIT':'CREATE'}</p><h2>${editing?'Edit reminder':'New reminder'}</h2></div><button type="button" class="icon-btn" onclick="closeModal()">×</button></div><label>Title<input id="f-title" autofocus value="${esc(r?.title||'')}" placeholder="e.g. Upload movie recommendation" required></label><div class="form-grid"><label>Category<select id="f-category">${Object.keys(categories).map(c=>`<option ${r?.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Type<select id="f-type"><option value="reminder" ${r?.type==='reminder'?'selected':''}>Reminder</option><option value="routine" ${r?.type==='routine'?'selected':''}>Routine</option><option value="smart" ${r?.type==='smart'?'selected':''}>Smart reminder</option></select></label><label>Date & time<input id="f-due" type="datetime-local" value="${localInputValue(due)}" required></label><label>Repeat<select id="f-repeat">${repeatOptions.map(x=>`<option ${r?.repeat===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Alert<select id="f-alert">${alertOptions.map(([label,value])=>`<option value="${value}" ${Number(r?.alertOffset||0)===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Priority<select id="f-priority"><option value="normal" ${r?.priority!=='important'?'selected':''}>Normal</option><option value="important" ${r?.priority==='important'?'selected':''}>Important</option></select></label></div><label>Context / notes<textarea id="f-notes" placeholder="Add prep steps, links or context…">${esc(r?.notes||'')}</textarea></label><div class="modal-actions">${editing?`<button type="button" class="danger-link" onclick="removeReminder('${r.id}',true)">Delete</button>`:''}<span class="modal-spacer"></span><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary" type="submit">${editing?'Save changes':'＋ Create reminder'}</button></div></form></div>`}
function closeModal(){state.modal=null;render()}
function saveReminderForm(e){e.preventDefault();const title=document.getElementById('f-title').value.trim();if(!title)return;const payload={title,category:document.getElementById('f-category').value,type:document.getElementById('f-type').value,priority:document.getElementById('f-priority').value,due:new Date(document.getElementById('f-due').value).toISOString(),repeat:document.getElementById('f-repeat').value,alertOffset:Number(document.getElementById('f-alert').value),notes:document.getElementById('f-notes').value.trim()};if(state.modal.mode==='edit'){reminders=reminders.map(r=>r.id===state.modal.id?{...r,...payload}:r);save();state.modal=null;showToast('Reminder updated')}else{reminders.unshift({id:crypto.randomUUID(),...payload,done:false,createdAt:new Date().toISOString()});save();state.modal=null;showToast('Reminder created')}}
function nextOccurrence(r){const d=new Date(r.due);if(r.repeat==='Daily')d.setDate(d.getDate()+1);else if(r.repeat==='Weekly')d.setDate(d.getDate()+7);else if(r.repeat==='Alternate days')d.setDate(d.getDate()+2);else if(r.repeat==='Monthly')d.setMonth(d.getMonth()+1);else if(r.repeat==='Weekdays'){do{d.setDate(d.getDate()+1)}while([0,6].includes(d.getDay()))}else return null;while(d<new Date()&&r.repeat!=='Smart check'){if(r.repeat==='Daily')d.setDate(d.getDate()+1);else if(r.repeat==='Weekly')d.setDate(d.getDate()+7);else if(r.repeat==='Alternate days')d.setDate(d.getDate()+2);else if(r.repeat==='Monthly')d.setMonth(d.getMonth()+1);else if(r.repeat==='Weekdays'){do{d.setDate(d.getDate()+1)}while([0,6].includes(d.getDay()))}else break}return d.toISOString()}
function completeReminder(id){const r=reminders.find(x=>x.id===id);if(!r)return;if(r.done){reminders=reminders.map(x=>x.id===id?{...x,done:false}:x);save();showToast('Reminder reopened');return}history.unshift({id:crypto.randomUUID(),reminderId:id,title:r.title,category:r.category,repeat:r.repeat,completedAt:new Date().toISOString()});const next=nextOccurrence(r);if(next){reminders=reminders.map(x=>x.id===id?{...x,due:next,done:false,lastCompletedAt:new Date().toISOString()}:x);save();showToast('Completed · next occurrence scheduled')}else{reminders=reminders.map(x=>x.id===id?{...x,done:true,completedAt:new Date().toISOString()}:x);save();showToast('Marked complete')}}
function openSnooze(id){state.snoozeId=id;render()}
function snoozeSheet(){return `<div class="sheet-backdrop" onclick="state.snoozeId=null;render()"><div class="snooze-sheet" onclick="event.stopPropagation()"><div class="sheet-handle"></div><p class="section-kicker">SNOOZE</p><h3>Remind me again</h3><div class="snooze-grid"><button onclick="snoozeBy(10)">10 min</button><button onclick="snoozeBy(30)">30 min</button><button onclick="snoozeBy(60)">1 hour</button><button onclick="snoozeTonight()">Tonight</button><button onclick="snoozeTomorrow()">Tomorrow 9 AM</button></div></div></div>`}
function snoozeBy(mins){reminders=reminders.map(r=>r.id===state.snoozeId?{...r,due:new Date(Date.now()+mins*60000).toISOString(),done:false}:r);save();state.snoozeId=null;showToast(`Snoozed ${mins<60?mins+' min':mins/60+' hour'}`)}
function snoozeTonight(){const d=new Date();d.setHours(20,0,0,0);if(d<new Date())d.setDate(d.getDate()+1);setSnoozeDate(d,'Snoozed until tonight')}
function snoozeTomorrow(){const d=addDays(new Date(),1);d.setHours(9,0,0,0);setSnoozeDate(d,'Snoozed until tomorrow morning')}
function setSnoozeDate(d,msg){reminders=reminders.map(r=>r.id===state.snoozeId?{...r,due:d.toISOString(),done:false}:r);save();state.snoozeId=null;showToast(msg)}
function removeReminder(id,fromModal=false){reminders=reminders.filter(r=>r.id!==id);save();if(fromModal)state.modal=null;showToast('Reminder deleted')}
function clearHistory(){if(!confirm('Clear completion history?'))return;history=[];save();showToast('History cleared')}
function notificationText(){if(!('Notification'in window))return'Notifications unavailable';return Notification.permission==='granted'?'Notifications enabled':'Enable notifications'}
async function requestNotifications(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');const p=await Notification.requestPermission();if(p==='granted'){new Notification('Pulse is ready',{body:'Notification permission is enabled.'});showToast('Notifications enabled')}else showToast('Notification permission not enabled')}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}
render();