const categories={Movies:['🎬','purple'],Content:['▶️','red'],Instagram:['◎','pink'],Personal:['⌂','blue'],Health:['✦','green'],'Game Dev':['🎮','amber'],Work:['▣','cyan']};
const starter=[
{id:'r1',title:'Daily movie recommendation',category:'Content',type:'routine',priority:'important',due:todayAt(19),repeat:'Daily',notes:'Pick movie → verify OTT India → prepare clip → caption.',done:false},
{id:'r2',title:'Telugu release tracker',category:'Movies',type:'smart',priority:'important',due:addDays(new Date(),1).toISOString(),repeat:'Smart check',notes:'Reconfirm release date from reliable sources before notifying.',done:false},
{id:'r3',title:'Frame of Today',category:'Instagram',type:'routine',priority:'normal',due:todayAt(20),repeat:'Alternate days',notes:'Choose cinematic frame set and finish colour composition.',done:false},
{id:'r4',title:'Game development practice',category:'Game Dev',type:'reminder',priority:'normal',due:addDays(new Date(),2).toISOString(),repeat:'Weekly',notes:'Unity + Blender learning session with one small playable outcome.',done:false}
];
function todayAt(h){const d=new Date();d.setHours(h,0,0,0);return d.toISOString()} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
let reminders=JSON.parse(localStorage.getItem('pulse.reminders')||'null')||starter;let state={tab:'today',filter:'All',query:'',dark:true,modal:false};
function save(){localStorage.setItem('pulse.reminders',JSON.stringify(reminders))}
function fmtDue(iso){const d=new Date(iso),n=new Date(),t=new Date();t.setDate(t.getDate()+1);let day=d.toDateString()===n.toDateString()?'Today':d.toDateString()===t.toDateString()?'Tomorrow':d.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});return day+' · '+d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){document.documentElement.dataset.theme=state.dark?'dark':'light';const open=reminders.filter(r=>!r.done).length,smart=reminders.filter(r=>r.type==='smart'&&!r.done).length,done=reminders.filter(r=>r.done).length;let visible=reminders.filter(r=>state.filter==='All'||r.category===state.filter).filter(r=>(r.title+' '+r.notes+' '+r.category).toLowerCase().includes(state.query.toLowerCase())).sort((a,b)=>new Date(a.due)-new Date(b.due));
app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">⚡</div><span>Pulse</span></div><nav>${nav('today','⌂','Today')}${nav('upcoming','▦','Upcoming')}${nav('automations','✦','Automations',smart)}${nav('all','☷','All reminders',open)}</nav><div class="sidebar-spacer"></div><button class="sidebar-action" onclick="requestNotifications()">🔔 Enable notifications</button><button class="sidebar-action" onclick="state.dark=!state.dark;render()">${state.dark?'☀️ Light mode':'🌙 Dark mode'}</button><button class="sidebar-action">⚙ Settings</button></aside><main class="main"><header class="topbar"><div><p class="eyebrow">PERSONAL COMMAND CENTER</p><h1>${state.tab==='today'?'Today':state.tab==='automations'?'Automations':state.tab==='upcoming'?'Upcoming':'All reminders'}</h1></div><div class="top-actions"><div class="search-box">⌕<input value="${esc(state.query)}" oninput="state.query=this.value;render()" placeholder="Search reminders"></div><button class="primary" onclick="state.modal=true;render()">＋ New reminder</button></div></header><section class="hero-grid"><div class="focus-card"><div class="focus-icon">✦</div><div><p class="muted">Focus for today</p><h2>${open===0?'You’re all clear.':open+' active reminders'}</h2><p class="muted small">${smart} smart checks are watching for you.</p></div><span class="chev">›</span></div><div class="stat-card"><span class="stat-label">Completed</span><strong>${done}</strong><span class="stat-foot">✓ logged</span></div><div class="stat-card"><span class="stat-label">Smart checks</span><strong>${smart}</strong><span class="stat-foot">⚡ active</span></div></section><section class="section-head"><div><p class="section-kicker">YOUR FLOW</p><h2>What needs your attention</h2></div><div class="chips">${['All',...Object.keys(categories)].slice(0,6).map(c=>`<button class="chip ${state.filter===c?'active':''}" onclick="state.filter='${c}';render()">${c}</button>`).join('')}</div></section><section class="reminder-list">${visible.length?visible.map(card).join(''):`<div class="empty"><div>✓</div><h3>Nothing here</h3><p>Try another filter or add a reminder.</p></div>`}</section><section class="automation-banner"><div class="automation-icon">✦</div><div><p class="section-kicker">AUTOMATION READY</p><h3>Reminders can become intelligent checks.</h3><p>V1 stores the workflow and schedule. Next we wire server-side checks, push delivery, Calendar sync and AI actions.</p></div><button class="secondary" onclick="state.tab='automations';render()">View automations</button></section></main><nav class="mobile-nav">${nav('today','⌂','Today')}${nav('upcoming','▦','Upcoming')}<button class="mobile-add" onclick="state.modal=true;render()">＋</button>${nav('automations','✦','Smart')}${nav('all','☷','All')}</nav>${state.modal?modal():''}</div>`}
function nav(id,icon,label,badge=''){return `<button class="nav-item ${state.tab===id?'active':''}" onclick="state.tab='${id}';render()"><span class="nav-icon">${icon}</span><span>${label}</span>${badge?`<b>${badge}</b>`:''}</button>`}
function card(r){const [icon,cls]=categories[r.category]||categories.Personal;return `<article class="reminder-card ${r.done?'done':''}"><button class="check" onclick="toggleDone('${r.id}')">${r.done?'✓':''}</button><div class="category-icon ${cls}">${icon}</div><div class="reminder-body"><div class="title-line"><h3>${esc(r.title)}</h3>${r.type==='smart'?'<span class="smart-tag">✦ Smart</span>':''}${r.priority==='important'?'<span class="priority-tag">🔥 Important</span>':''}</div><p>${esc(r.notes)}</p><div class="meta-row"><span>◷ ${fmtDue(r.due)}</span><span>↻ ${esc(r.repeat)}</span><span class="cat-dot ${cls}">${r.category}</span></div></div><div class="card-actions">${!r.done?`<button title="Snooze 30 min" onclick="snooze('${r.id}')">↻</button>`:''}<button title="Delete" onclick="removeReminder('${r.id}')">⌫</button><button>•••</button></div></article>`}
function modal(){const d=new Date(Date.now()+3600000);const local=new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);return `<div class="modal-backdrop" onclick="state.modal=false;render()"><form class="modal" onclick="event.stopPropagation()" onsubmit="createReminder(event)"><div class="modal-head"><div><p class="section-kicker">CREATE</p><h2>New reminder</h2></div><button type="button" class="icon-btn" onclick="state.modal=false;render()">×</button></div><label>Title<input id="f-title" autofocus placeholder="e.g. Upload movie recommendation"></label><div class="form-grid"><label>Category<select id="f-category">${Object.keys(categories).map(c=>`<option>${c}</option>`).join('')}</select></label><label>Type<select id="f-type"><option value="reminder">Reminder</option><option value="routine">Routine</option><option value="smart">Smart reminder</option></select></label><label>Date & time<input id="f-due" type="datetime-local" value="${local}"></label><label>Repeat<select id="f-repeat"><option>Never</option><option>Daily</option><option>Weekly</option><option>Alternate days</option><option>Weekdays</option><option>Smart check</option></select></label><label>Priority<select id="f-priority"><option value="normal">Normal</option><option value="important">Important</option></select></label></div><label>Context / notes<textarea id="f-notes" placeholder="Add what you need to do, prep steps or context…"></textarea></label><div class="modal-actions"><button type="button" class="secondary" onclick="state.modal=false;render()">Cancel</button><button class="primary" type="submit">＋ Create reminder</button></div></form></div>`}
function createReminder(e){e.preventDefault();const title=document.getElementById('f-title').value.trim();if(!title)return;reminders.unshift({id:crypto.randomUUID(),title,category:document.getElementById('f-category').value,type:document.getElementById('f-type').value,priority:document.getElementById('f-priority').value,due:new Date(document.getElementById('f-due').value).toISOString(),repeat:document.getElementById('f-repeat').value,notes:document.getElementById('f-notes').value,done:false});save();state.modal=false;render()}
function toggleDone(id){reminders=reminders.map(r=>r.id===id?{...r,done:!r.done}:r);save();render()}function snooze(id){reminders=reminders.map(r=>r.id===id?{...r,due:new Date(new Date(r.due).getTime()+1800000).toISOString()}:r);save();render()}function removeReminder(id){reminders=reminders.filter(r=>r.id!==id);save();render()}
async function requestNotifications(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');const p=await Notification.requestPermission();if(p==='granted')new Notification('Pulse is ready',{body:'Browser notification permission is enabled.'})}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}
render();