// Pulse V5.1.0 — Calendar View
(()=>{const VERSION='5.1.0';
const cal={view:localStorage.getItem('pulse.calendar.view')||'month',anchor:new Date(localStorage.getItem('pulse.calendar.anchor')||Date.now()),selected:new Date(localStorage.getItem('pulse.calendar.selected')||Date.now())};
const pad=n=>String(n).padStart(2,'0'),ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,same=(a,b)=>ymd(a)===ymd(b),startDay=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()),add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x},startWeek=d=>{let x=startDay(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);return x};
const eventsFor=d=>reminders.filter(r=>r.enabled&&r.due&&same(new Date(r.due),d)).sort((a,b)=>new Date(a.due)-new Date(b.due));
const time=i=>new Date(i).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),monthName=d=>d.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),dayName=d=>d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
function persist(){localStorage.setItem('pulse.calendar.view',cal.view);localStorage.setItem('pulse.calendar.anchor',cal.anchor.toISOString());localStorage.setItem('pulse.calendar.selected',cal.selected.toISOString())}
function setView(v){cal.view=v;if(v==='day')cal.anchor=new Date(cal.selected);persist();render()}
function move(n){if(cal.view==='month')cal.anchor=new Date(cal.anchor.getFullYear(),cal.anchor.getMonth()+n,1);else if(cal.view==='week')cal.anchor=add(cal.anchor,n*7);else{cal.anchor=add(cal.anchor,n);cal.selected=new Date(cal.anchor)}persist();render()}
function todayCal(){cal.anchor=new Date();cal.selected=new Date();persist();render()}
function pickDate(s){let d=new Date(s+'T12:00:00');cal.selected=d;cal.anchor=d;cal.view='day';persist();render()}
function openEvent(id,e){e?.stopPropagation();openDetail(id)}
window.pulseCalendarSetView=setView;window.pulseCalendarMove=move;window.pulseCalendarToday=todayCal;window.pulseCalendarPickDate=pickDate;window.pulseCalendarOpenEvent=openEvent;
function controls(label){return `<div class="v510-cal-head"><div class="v510-cal-title"><h2>${esc(label)}</h2><div class="v510-cal-controls"><button class="secondary" onclick="pulseCalendarMove(-1)">‹</button><button class="secondary" onclick="pulseCalendarToday()">Today</button><button class="secondary" onclick="pulseCalendarMove(1)">›</button></div></div><div class="v510-cal-views"><button class="secondary ${cal.view==='month'?'active':''}" onclick="pulseCalendarSetView('month')">Month</button><button class="secondary ${cal.view==='week'?'active':''}" onclick="pulseCalendarSetView('week')">Week</button><button class="secondary ${cal.view==='day'?'active':''}" onclick="pulseCalendarSetView('day')">Day</button></div></div>`}
function eventButton(r){return `<button class="v510-event" data-reminder-id="${r.id}" onclick="pulseCalendarOpenEvent('${r.id}',event)" title="${esc(r.title)}"><b>${esc(r.title)}</b><small>${time(r.due)} · ${esc(r.category)}</small></button>`}
function monthView(){let first=new Date(cal.anchor.getFullYear(),cal.anchor.getMonth(),1),offset=(first.getDay()+6)%7,start=add(first,-offset),today=new Date(),cells=[];for(let i=0;i<42;i++){let d=add(start,i),ev=eventsFor(d),outside=d.getMonth()!==first.getMonth(),ds=ymd(d);cells.push(`<div class="v510-daycell ${outside?'muted-day':''} ${same(d,today)?'today-cell':''}" data-date="${ds}" data-has-events="${ev.length?'1':'0'}" onclick="pulseCalendarPickDate('${ds}')"><div class="v510-date-num"><span>${d.getDate()}</span>${ev.length?`<small>${ev.length}</small>`:''}</div>${ev.slice(0,3).map(eventButton).join('')}${ev.length>3?`<div class="v510-more">+${ev.length-3} more</div>`:''}</div>`)}return `${controls(monthName(first))}<div class="v510-month-wrap"><div class="v510-month">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="v510-weekday">${x}</div>`).join('')}${cells.join('')}</div></div>`}
function weekView(){let start=startWeek(cal.anchor),end=add(start,6),today=new Date(),cols=[];for(let i=0;i<7;i++){let d=add(start,i),ev=eventsFor(d);cols.push(`<section class="v510-week-col ${same(d,today)?'today-col':''}"><div class="v510-week-head"><b>${d.toLocaleDateString('en-IN',{weekday:'short'})}</b><small>${d.toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div><div class="v510-week-events">${ev.length?ev.map(eventButton).join(''):'<div class="v510-week-empty">No reminders</div>'}</div></section>`)}return `${controls(`${start.toLocaleDateString('en-IN',{day:'numeric',month:'short'})} – ${end.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}`)}<div class="v510-week">${cols.join('')}</div>`}
function dayView(){let d=cal.anchor,ev=eventsFor(d);return `${controls(dayName(d))}<div class="v510-agenda"><div class="v510-agenda-date"><div><p class="section-kicker">${same(d,new Date())?'TODAY':'AGENDA'}</p><b>${ev.length} reminder${ev.length===1?'':'s'}</b></div><button class="primary" onclick="openCreate()">＋ New reminder</button></div>${ev.length?`<div class="v510-agenda-list">${ev.map(r=>`<article class="v510-agenda-item" data-reminder-id="${r.id}" onclick="pulseCalendarOpenEvent('${r.id}',event)"><div class="v510-agenda-time">${time(r.due)}</div><div><h3>${esc(r.title)}</h3><p><span class="v510-cat-dot"></span>${esc(r.category)} · ${esc(r.repeat||'Never')}${r.priority==='important'?' · Important':''}</p></div><span>›</span></article>`).join('')}</div>`:'<div class="v510-calendar-empty">No reminders scheduled for this day.</div>'}</div>`}
function calendarView(){return `<section class="v510-calendar">${cal.view==='month'?monthView():cal.view==='week'?weekView():dayView()}</section>`}
const oldTitle=window.title,oldSubtitle=window.subtitle;window.title=function(){return state.tab==='calendar'?'Calendar':oldTitle()};window.subtitle=function(){return state.tab==='calendar'?'See your Pulse reminders across days, weeks and months.':oldSubtitle()};
const oldLayout=window.layout;window.layout=function(body){oldLayout(body);const side=document.querySelector('.sidebar nav');if(side&&!side.querySelector('[data-v510-calendar]')){const btn=document.createElement('button');btn.className=`nav-item v510-sidebar-calendar ${state.tab==='calendar'?'active':''}`;btn.dataset.v510Calendar='1';btn.onclick=()=>go('calendar');btn.innerHTML='<span>▦</span><span>Calendar</span>';const upcoming=[...side.querySelectorAll('.nav-item')].find(x=>x.textContent.includes('Upcoming'));upcoming?.after(btn)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('[data-v510-calendar]')){const btn=document.createElement('button');btn.className=`nav-item v510-mobile-calendar ${state.tab==='calendar'?'active':''}`;btn.dataset.v510Calendar='1';btn.onclick=()=>go('calendar');btn.innerHTML='<span>▦</span><span>Calendar</span>';const upcoming=[...mobile.querySelectorAll('.nav-item')].find(x=>x.textContent.includes('Upcoming'));upcoming?.after(btn)}};
const oldRender=window.render;window.render=function(){if(state.tab==='calendar')layout(calendarView());else oldRender();document.querySelectorAll('.brand small').forEach(x=>x.textContent='V'+VERSION);document.querySelectorAll('.version-box b').forEach(x=>x.textContent='Pulse '+VERSION)};
window.PULSE_VERSION=VERSION;render();
})();