// Pulse V7.0G — cloud/auth shell
// Auth, account bootstrap and cloud UI live here. Reminder sync is owned by PulseSync.
const PULSE_SUPABASE_URL='https://oofvayrslzpdnlameaqg.supabase.co';
const PULSE_SUPABASE_KEY='sb_publishable_C3GVsS3Gf6jzqNCu3MEzPA_3eCb4YlS';
const pulseCloud=window.supabase.createClient(PULSE_SUPABASE_URL,PULSE_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let pulseUser=null,pulseSyncing=false,pulsePulling=false,pulseRealtime=null,pulseSyncTimer=null;
const pulseLocalSave=save;
const pulseNotificationGranted=()=>('Notification'in window&&Notification.permission==='granted');

function pulseWaitForSync(){if(window.PulseSync)return Promise.resolve(window.PulseSync);return new Promise((resolve,reject)=>{let done=false;const finish=e=>{if(done)return;done=true;clearTimeout(t);resolve(e?.detail||window.PulseSync)};window.addEventListener('pulse:sync-ready',finish,{once:true});const t=setTimeout(()=>{if(done)return;done=true;window.removeEventListener('pulse:sync-ready',finish);reject(new Error('Pulse sync engine did not initialize.'))},10000)})}
async function pulsePushAll(){const sync=await pulseWaitForSync();return sync.pushAll()}
async function pulsePullAll(){const sync=await pulseWaitForSync();return sync.pullAll()}
function pulseDbReminder(r){if(window.PulseSync)return PulseSync.toDbReminder(r);throw new Error('Pulse sync engine is not ready.')}
function pulseAlertOffsets(r){if(window.PulseSync)return PulseSync.offsets(r);const raw=Array.isArray(r.alertOffsets)?r.alertOffsets:[Number(r.alertOffset??settings.defaultAlert??0)];const out=[...new Set(raw.map(Number).filter(n=>Number.isFinite(n)&&n>=0))].sort((a,b)=>b-a);return out.length?out:[0]}
async function pulseStartRealtime(){return false}

save=function(){pulseLocalSave();if(pulseUser&&!pulsePulling){clearTimeout(pulseSyncTimer);pulseSyncTimer=setTimeout(()=>pulsePushAll().catch(pulseCloudError),500)}};
function pulseCloudError(err){console.error('Pulse cloud',err);pulseSetCloudBadge('Sync error','error');if(typeof toast==='function')toast('Cloud sync issue — local copy is safe')}
function pulseSetCloudBadge(text,state='ok'){document.querySelectorAll('.sync-pill').forEach(el=>{el.classList.toggle('cloud-ok',state==='ok');el.classList.toggle('cloud-error',state==='error');let b=el.querySelector('b'),s=el.querySelector('small');if(b)b.textContent=pulseUser?'Cloud sync':'Local mode';if(s)s.textContent=text})}
function pulseAuthOverlay(){if(document.getElementById('pulse-auth'))return;let el=document.createElement('div');el.id='pulse-auth';el.className='cloud-auth-backdrop';el.innerHTML=`<section class="cloud-auth-card"><div class="cloud-auth-logo">⚡</div><p class="section-kicker">PULSE CLOUD</p><h1>Sync your reminders</h1><p>Sign in with your email to keep Pulse in sync across your phone and computer.</p><form onsubmit="pulseSendMagicLink(event)"><label>Email address<input id="pulse-auth-email" type="email" autocomplete="email" placeholder="you@example.com" required></label><button class="primary" type="submit">Email me a sign-in link</button></form><button class="cloud-skip" onclick="pulseCloseAuth()">Continue in local mode</button><small>Your existing local reminders stay on this device until you sign in.</small></section>`;document.body.appendChild(el)}
function pulseCloseAuth(){document.getElementById('pulse-auth')?.remove()}
async function pulseSendMagicLink(e){e.preventDefault();let email=document.getElementById('pulse-auth-email').value.trim(),btn=e.submitter;btn.disabled=true;btn.textContent='Sending…';let {error}=await pulseCloud.auth.signInWithOtp({email,options:{emailRedirectTo:'https://pulse-reminder.vercel.app'}});if(error){btn.disabled=false;btn.textContent='Email me a sign-in link';alert(error.message);return}document.querySelector('.cloud-auth-card').innerHTML=`<div class="cloud-auth-logo">✉</div><p class="section-kicker">CHECK YOUR EMAIL</p><h1>Sign-in link sent</h1><p>Open the email from Supabase and tap the secure sign-in link. Pulse will return here and start syncing.</p><button class="secondary" onclick="pulseCloseAuth()">Continue locally for now</button>`}
async function pulseSignOut(){await pulseCloud.auth.signOut();pulseUser=null;if(pulseRealtime){await pulseCloud.removeChannel(pulseRealtime);pulseRealtime=null}render();pulseAuthOverlay()}
async function pulseEnsureAccount(){let u=pulseUser;if(!u)return;let q=await pulseCloud.from('profiles').upsert({id:u.id,display_name:u.email?.split('@')[0]||'Pulse user',timezone:settings.timezone||'Asia/Kolkata'},{onConflict:'id'});if(q.error)throw q.error;q=await pulseCloud.from('user_settings').upsert({user_id:u.id,theme:settings.theme||'dark',timezone:settings.timezone||'Asia/Kolkata',default_alert_minutes:Number(settings.defaultAlert??15),notifications_enabled:pulseNotificationGranted(),persistent_notifications:!!settings.persistentByDefault,settings:{}},{onConflict:'user_id'});if(q.error)throw q.error}

async function pulseAfterLogin(session){pulseUser=session.user;pulseCloseAuth();await pulseEnsureAccount();await pulseWaitForSync();let {count,error}=await pulseCloud.from('reminders').select('*',{count:'exact',head:true}).eq('user_id',pulseUser.id).is('deleted_at',null);if(error)throw error;if((count||0)===0&&reminders.length)await pulsePushAll();else await pulsePullAll();await pulseStartRealtime();render();pulseSetCloudBadge('Cloud connected')}
function pulsePatchSettingsUI(){let card=document.querySelector('.settings-grid');if(!card||document.getElementById('cloud-account-card'))return;let a=document.createElement('article');a.id='cloud-account-card';a.className='settings-card';a.innerHTML=`<h2>Pulse account</h2>${pulseUser?`<div class="status-line"><span class="status-dot"></span><div><b>${pulseUser.email||'Signed in'}</b><p>Cloud sync is active on this device.</p></div></div><button class="secondary" onclick="pulsePushAll().then(()=>toast('Cloud sync complete')).catch(pulseCloudError)">Sync now</button><button class="danger-link" onclick="pulseSignOut()">Sign out</button>`:`<p class="muted">Not signed in. Reminders are only stored on this device.</p><button class="secondary" onclick="pulseAuthOverlay()">Sign in to Pulse</button>`}`;card.prepend(a)}
function pulsePatchCloudUI(){pulsePatchSettingsUI();if(pulseUser)pulseSetCloudBadge('Cloud connected')}
window.addEventListener('pulse:runtime-ready',e=>e.detail?.afterRender?.(pulsePatchCloudUI),{once:true});
setTimeout(pulsePatchCloudUI,0);

(async()=>{try{let {data:{session}}=await pulseCloud.auth.getSession();if(session)await pulseAfterLogin(session);else{pulseAuthOverlay();pulseSetCloudBadge('Sign in to sync')}}catch(e){pulseCloudError(e)}})();
pulseCloud.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session&&!pulseUser)pulseAfterLogin(session).catch(pulseCloudError);if(event==='SIGNED_OUT'){pulseUser=null;render();pulseAuthOverlay()}});
