const PULSE_SUPABASE_URL='https://oofvayrslzpdnlameaqg.supabase.co';
const PULSE_SUPABASE_KEY='sb_publishable_C3GVsS3Gf6jzqNCu3MEzPA_3eCb4YlS';
const pulseCloud=window.supabase.createClient(PULSE_SUPABASE_URL,PULSE_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let pulseUser=null,pulseSyncing=false,pulsePulling=false,pulseRealtime=null,pulseSyncTimer=null;
const pulseLocalSave=save;
save=function(){pulseLocalSave();if(pulseUser&&!pulsePulling){clearTimeout(pulseSyncTimer);pulseSyncTimer=setTimeout(()=>pulsePushAll().catch(pulseCloudError),500)}};
function pulseCloudError(err){console.error('Pulse cloud',err);pulseSetCloudBadge('Sync error','error');if(typeof toast==='function')toast('Cloud sync issue — local copy is safe')}
function pulseSetCloudBadge(text,state='ok'){document.querySelectorAll('.sync-pill').forEach(el=>{el.classList.toggle('cloud-ok',state==='ok');el.classList.toggle('cloud-error',state==='error');let b=el.querySelector('b'),s=el.querySelector('small');if(b)b.textContent=pulseUser?'Cloud sync':'Local mode';if(s)s.textContent=text})}
function pulseAuthOverlay(){if(document.getElementById('pulse-auth'))return;let el=document.createElement('div');el.id='pulse-auth';el.className='cloud-auth-backdrop';el.innerHTML=`<section class="cloud-auth-card"><div class="cloud-auth-logo">⚡</div><p class="section-kicker">PULSE CLOUD</p><h1>Sync your reminders</h1><p>Sign in with your email to keep Pulse in sync across your phone and computer.</p><form onsubmit="pulseSendMagicLink(event)"><label>Email address<input id="pulse-auth-email" type="email" autocomplete="email" placeholder="you@example.com" required></label><button class="primary" type="submit">Email me a sign-in link</button></form><button class="cloud-skip" onclick="pulseCloseAuth()">Continue in local mode</button><small>Your existing local reminders stay on this device until you sign in.</small></section>`;document.body.appendChild(el)}
function pulseCloseAuth(){document.getElementById('pulse-auth')?.remove()}
async function pulseSendMagicLink(e){e.preventDefault();let email=document.getElementById('pulse-auth-email').value.trim(),btn=e.submitter;btn.disabled=true;btn.textContent='Sending…';let {error}=await pulseCloud.auth.signInWithOtp({email,options:{emailRedirectTo:'https://pulse-reminder.vercel.app'}});if(error){btn.disabled=false;btn.textContent='Email me a sign-in link';alert(error.message);return}document.querySelector('.cloud-auth-card').innerHTML=`<div class="cloud-auth-logo">✉</div><p class="section-kicker">CHECK YOUR EMAIL</p><h1>Sign-in link sent</h1><p>Open the email from Supabase and tap the secure sign-in link. Pulse will return here and start syncing.</p><button class="secondary" onclick="pulseCloseAuth()">Continue locally for now</button>`}
async function pulseSignOut(){await pulseCloud.auth.signOut();pulseUser=null;if(pulseRealtime){await pulseCloud.removeChannel(pulseRealtime);pulseRealtime=null}render();pulseAuthOverlay()}
async function pulseEnsureAccount(){let u=pulseUser;if(!u)return;await pulseCloud.from('profiles').upsert({id:u.id,display_name:u.email?.split('@')[0]||'Pulse user',timezone:settings.timezone||'Asia/Kolkata'},{onConflict:'id'});await pulseCloud.from('user_settings').upsert({user_id:u.id,theme:settings.theme||'dark',timezone:settings.timezone||'Asia/Kolkata',default_alert_minutes:Number(settings.defaultAlert??15),notifications_enabled:Notification.permission==='granted',persistent_notifications:!!settings.persistentByDefault,settings:{}},{onConflict:'user_id'})}
function pulseDbReminder(r){return{user_id:pulseUser.id,title:r.title,notes:r.notes||'',category:r.category||'Personal',reminder_type:r.type||'reminder',priority:r.priority||'normal',status:r.enabled===false?'paused':'active',due_at:r.due||null,timezone:settings.timezone||'Asia/Kolkata',recurrence_rule:null,recurrence_label:r.repeat||'Never',persistent:!!r.persistent,calendar_sync_mode:'off',source_local_id:String(r.id),completed_at:null,archived_at:null,deleted_at:null}}
async function pulsePushAll(){if(!pulseUser||pulseSyncing)return;pulseSyncing=true;pulseSetCloudBadge('Syncing…');try{await pulseEnsureAccount();let rows=reminders.map(pulseDbReminder);let cloudMap=new Map();if(rows.length){let {data,error}=await pulseCloud.from('reminders').upsert(rows,{onConflict:'user_id,source_local_id'}).select('id,source_local_id');if(error)throw error;data.forEach(x=>cloudMap.set(x.source_local_id,x.id))}let {data:remote,error:fetchErr}=await pulseCloud.from('reminders').select('id,source_local_id').eq('user_id',pulseUser.id).is('deleted_at',null);if(fetchErr)throw fetchErr;let localIds=new Set(reminders.map(r=>String(r.id))),gone=(remote||[]).filter(x=>x.source_local_id&&!localIds.has(x.source_local_id)).map(x=>x.id);if(gone.length){let {error}=await pulseCloud.from('reminders').update({deleted_at:new Date().toISOString(),status:'deleted'}).in('id',gone);if(error)throw error}
await pulseCloud.from('reminder_subtasks').delete().eq('user_id',pulseUser.id);let subRows=[];for(let r of reminders){let rid=cloudMap.get(String(r.id))||remote?.find(x=>x.source_local_id===String(r.id))?.id;if(!rid)continue;(r.subtasks||[]).forEach((title,i)=>subRows.push({reminder_id:rid,user_id:pulseUser.id,title,is_completed:(r.completedSubtasks||[]).includes(i),position:i,completed_at:(r.completedSubtasks||[]).includes(i)?new Date().toISOString():null}))}if(subRows.length){let {error}=await pulseCloud.from('reminder_subtasks').insert(subRows);if(error)throw error}
await pulseCloud.from('reminder_alerts').delete().eq('user_id',pulseUser.id).eq('status','pending');let alertRows=[];for(let r of reminders){let rid=cloudMap.get(String(r.id))||remote?.find(x=>x.source_local_id===String(r.id))?.id;if(!rid||!r.due)continue;let off=Number(r.alertOffset||0);alertRows.push({reminder_id:rid,user_id:pulseUser.id,alert_at:new Date(new Date(r.due).getTime()-off*60000).toISOString(),offset_minutes:off,status:'pending'})}if(alertRows.length){let {error}=await pulseCloud.from('reminder_alerts').insert(alertRows);if(error)throw error}
let hRows=history.map(h=>({user_id:pulseUser.id,reminder_id:null,reminder_title:h.title||h.snapshot?.title||'Reminder',action:'completed',occurred_at:h.completedAt||new Date().toISOString(),metadata:{category:h.category||h.snapshot?.category||'Personal',snapshot:h.snapshot||null},source_local_id:String(h.hid||crypto.randomUUID())}));if(hRows.length){let {error}=await pulseCloud.from('completion_history').upsert(hRows,{onConflict:'user_id,source_local_id'});if(error)throw error}
await pulseCloud.from('user_settings').upsert({user_id:pulseUser.id,theme:settings.theme||'dark',timezone:settings.timezone||'Asia/Kolkata',default_alert_minutes:Number(settings.defaultAlert??15),notifications_enabled:Notification.permission==='granted',persistent_notifications:!!settings.persistentByDefault,settings:{}},{onConflict:'user_id'});localStorage.setItem('pulse.cloud.migrated.'+pulseUser.id,'1');pulseSetCloudBadge('Synced just now')}finally{pulseSyncing=false}}
async function pulsePullAll(){if(!pulseUser||pulsePulling)return;pulsePulling=true;try{let [{data:rr,error:re},{data:ss,error:se},{data:aa,error:ae},{data:hh,error:he},{data:us,error:ue}]=await Promise.all([pulseCloud.from('reminders').select('*').eq('user_id',pulseUser.id).is('deleted_at',null).is('archived_at',null),pulseCloud.from('reminder_subtasks').select('*').eq('user_id',pulseUser.id).order('position'),pulseCloud.from('reminder_alerts').select('*').eq('user_id',pulseUser.id),pulseCloud.from('completion_history').select('*').eq('user_id',pulseUser.id).order('occurred_at',{ascending:false}),pulseCloud.from('user_settings').select('*').eq('user_id',pulseUser.id).maybeSingle()]);if(re||se||ae||he||ue)throw(re||se||ae||he||ue);let subs=new Map();(ss||[]).forEach(x=>{if(!subs.has(x.reminder_id))subs.set(x.reminder_id,[]);subs.get(x.reminder_id).push(x)});let alertsBy=new Map();(aa||[]).filter(x=>x.status==='pending').forEach(x=>{if(!alertsBy.has(x.reminder_id))alertsBy.set(x.reminder_id,x)});reminders=(rr||[]).map(x=>{let st=subs.get(x.id)||[],al=alertsBy.get(x.id);return{id:x.source_local_id||x.id,title:x.title,category:x.category,type:x.reminder_type==='automation'?'smart':x.reminder_type,priority:x.priority,due:x.due_at,repeat:x.recurrence_label||'Never',alertOffset:al?.offset_minutes??0,notes:x.notes||'',enabled:x.status!=='paused',persistent:!!x.persistent,subtasks:st.map(y=>y.title),completedSubtasks:st.map((y,i)=>y.is_completed?i:null).filter(i=>i!==null),lastResult:null}});history=(hh||[]).map(x=>({hid:x.source_local_id||x.id,title:x.reminder_title,category:x.metadata?.category||'Personal',completedAt:x.occurred_at,snapshot:x.metadata?.snapshot||null}));if(us){settings={...settings,theme:us.theme==='system'?'dark':us.theme,timezone:us.timezone,defaultAlert:us.default_alert_minutes,persistentByDefault:us.persistent_notifications}}pulseLocalSave();render();pulseSetCloudBadge('Synced from cloud')}finally{pulsePulling=false}}
async function pulseStartRealtime(){if(pulseRealtime)await pulseCloud.removeChannel(pulseRealtime);let t;const refresh=()=>{clearTimeout(t);t=setTimeout(()=>{if(!pulseSyncing)pulsePullAll().catch(pulseCloudError)},600)};pulseRealtime=pulseCloud.channel('pulse-'+pulseUser.id).on('postgres_changes',{event:'*',schema:'public',table:'reminders',filter:`user_id=eq.${pulseUser.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'reminder_subtasks',filter:`user_id=eq.${pulseUser.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'completion_history',filter:`user_id=eq.${pulseUser.id}`},refresh).subscribe()}
async function pulseAfterLogin(session){pulseUser=session.user;pulseCloseAuth();await pulseEnsureAccount();let {count,error}=await pulseCloud.from('reminders').select('*',{count:'exact',head:true}).eq('user_id',pulseUser.id).is('deleted_at',null);if(error)throw error;if((count||0)===0&&reminders.length){await pulsePushAll()}else{await pulsePullAll()}await pulseStartRealtime();render();pulseSetCloudBadge('Cloud connected')}
function pulsePatchSettingsUI(){let card=document.querySelector('.settings-grid');if(!card||document.getElementById('cloud-account-card'))return;let a=document.createElement('article');a.id='cloud-account-card';a.className='settings-card';a.innerHTML=`<h2>Pulse account</h2>${pulseUser?`<div class="status-line"><span class="status-dot"></span><div><b>${pulseUser.email||'Signed in'}</b><p>Cloud sync is active on this device.</p></div></div><button class="secondary" onclick="pulsePushAll().then(()=>toast('Cloud sync complete')).catch(pulseCloudError)">Sync now</button><button class="danger-link" onclick="pulseSignOut()">Sign out</button>`:`<p class="muted">Not signed in. Reminders are only stored on this device.</p><button class="secondary" onclick="pulseAuthOverlay()">Sign in to Pulse</button>`}`;card.prepend(a)}
const pulseOriginalRender=render;render=function(){pulseOriginalRender();pulsePatchSettingsUI();if(pulseUser)pulseSetCloudBadge('Cloud connected')};
(async()=>{try{let {data:{session}}=await pulseCloud.auth.getSession();if(session)await pulseAfterLogin(session);else{pulseAuthOverlay();pulseSetCloudBadge('Sign in to sync')}}catch(e){pulseCloudError(e)}})();
pulseCloud.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session&&!pulseUser)pulseAfterLogin(session).catch(pulseCloudError);if(event==='SIGNED_OUT'){pulseUser=null;render();pulseAuthOverlay()}});
