const PULSE_VAPID_PUBLIC_KEY='BGZO-2Fixle66XVngosS3CKGJjkE4ge_Eau3RldyQxBG7-7yaMS8TwxjQFlDxe5CmvLXU3rM3_hVuyJ3V-qGg48';
function pulseB64ToUint8(base64String){const padding='='.repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function pulseIsIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1}
function pulseIsStandalone(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function pulsePushSupported(){return 'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function pulsePlatform(){if(pulseIsIOS())return'ios';if(/Android/i.test(navigator.userAgent))return'android';if(/Windows/i.test(navigator.userAgent))return'windows';if(/Mac/i.test(navigator.userAgent))return'macos';return'web'}
function pulseDeviceName(){let p=pulsePlatform();return `${p[0].toUpperCase()+p.slice(1)} · ${navigator.userAgentData?.brands?.[0]?.brand||navigator.appName||'Browser'}`}
async function pulseSavePushSubscription(sub){if(!pulseUser)throw new Error('Sign in to Pulse before enabling push notifications.');let j=sub.toJSON(),row={user_id:pulseUser.id,device_name:pulseDeviceName(),platform:pulsePlatform(),push_endpoint:j.endpoint,push_p256dh:j.keys?.p256dh||'',push_auth:j.keys?.auth||'',is_active:true,last_seen_at:new Date().toISOString()};let {data:found,error:qErr}=await pulseCloud.from('devices').select('id').eq('user_id',pulseUser.id).eq('push_endpoint',j.endpoint).maybeSingle();if(qErr)throw qErr;if(found?.id){let {error}=await pulseCloud.from('devices').update({...row,updated_at:new Date().toISOString()}).eq('id',found.id);if(error)throw error;localStorage.setItem('pulse.device.id',found.id);return found.id}let {data,error}=await pulseCloud.from('devices').insert(row).select('id').single();if(error)throw error;localStorage.setItem('pulse.device.id',data.id);return data.id}
async function pulseRegisterPush(){if(!pulseUser){pulseAuthOverlay();throw new Error('Sign in first, then enable notifications.')}if(pulseIsIOS()&&!pulseIsStandalone())throw new Error('On iPhone, add Pulse to your Home Screen and open it from there before enabling notifications.');if(!pulsePushSupported())throw new Error('Web Push is not supported in this browser.');let permission=Notification.permission;if(permission!=='granted')permission=await Notification.requestPermission();if(permission!=='granted')throw new Error(permission==='denied'?'Notifications are blocked in browser/system settings.':'Notification permission was not granted.');let reg=await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:pulseB64ToUint8(PULSE_VAPID_PUBLIC_KEY)});await pulseSavePushSubscription(sub);settings.notificationsEnabled=true;pulseLocalSave?.();await pulseCloud.from('user_settings').upsert({user_id:pulseUser.id,notifications_enabled:true,theme:settings.theme||'dark',timezone:settings.timezone||'Asia/Kolkata',default_alert_minutes:Number(settings.defaultAlert??15),persistent_notifications:!!settings.persistentByDefault,settings:{}},{onConflict:'user_id'});return sub}
async function requestNotifications(){try{await pulseRegisterPush();toast('Push notifications connected ✓');render()}catch(e){console.error('Pulse push',e);toast(e.message||'Could not enable notifications');alert(e.message||'Could not enable notifications')}}
function notificationText(){if(!('Notification'in window))return'Notifications unavailable';if(Notification.permission==='denied')return'Notifications blocked';if(Notification.permission==='granted')return'Notifications enabled';return'Enable notifications'}
async function pulseTestPush(){try{await pulseRegisterPush();let {data:{session}}=await pulseCloud.auth.getSession();if(!session)throw new Error('Sign in first.');let res=await fetch(PULSE_SUPABASE_URL+'/functions/v1/process-reminders',{method:'POST',headers:{'Content-Type':'application/json','apikey':PULSE_SUPABASE_KEY,'Authorization':'Bearer '+session.access_token},body:JSON.stringify({mode:'test'})});let out=await res.json();if(!res.ok||!out.ok)throw new Error(out.error||'Test push failed');toast(`Test push sent to ${out.sent} device${out.sent===1?'':'s'}`)}catch(e){console.error(e);alert(e.message||'Test push failed')}}
function pulsePushSettingsCard(){if(state.tab!=='settings'||document.getElementById('push-test-card'))return;let grid=document.querySelector('.settings-grid');if(!grid)return;let el=document.createElement('article');el.id='push-test-card';el.className='settings-card';el.innerHTML=`<h2>Push delivery</h2><p class="muted">Register this device with Pulse, then send an immediate server-side test.</p><button class="secondary" onclick="requestNotifications()">Enable on this device</button><button class="secondary" onclick="pulseTestPush()">Send test push now</button><small>${pulseIsIOS()&&!pulseIsStandalone()?'iPhone requires Pulse to be added to the Home Screen for Web Push.':'This tests the real Supabase → Web Push → device path.'}</small>`;grid.prepend(el)}
const pulsePushRender=render;render=function(){pulsePushRender();pulsePushSettingsCard()};
(async()=>{try{if(pulsePushSupported()&&Notification.permission==='granted'&&pulseUser){let reg=await navigator.serviceWorker.register('/sw.js');let sub=await reg.pushManager.getSubscription();if(sub)await pulseSavePushSubscription(sub)}}catch(e){console.warn('Pulse push refresh',e)}})();