// Pulse V7.0B compatibility adapter — recurrence UI + legacy globals
(()=>{
const engine=window.PulseRecurrence;
if(!engine){console.error('PulseRecurrence engine missing');return}
const types=engine.TYPES,days=engine.DAYS;
const cfg=r=>engine.normalize(r||{});
const label=c=>engine.label(c);
function ui(r){let c=cfg(r);return `<section class="v427-recur"><div class="v42-field-title">Repeat</div><select id="fr427">${types.map(x=>`<option ${c.type===x?'selected':''}>${x}</option>`).join('')}</select><div class="v427-options"><label>Interval<input id="finterval" type="number" min="1" max="365" value="${c.interval}"><small>Used by Every X days/weeks</small></label><label>Monthly date<input id="fmonthday" type="number" min="1" max="31" value="${c.monthDay}"></label><label>After completion<input id="fafter" type="number" min="1" max="365" value="${c.afterDays}"><small>Days after you complete it</small></label></div><div class="v427-days">${days.map(([n,v])=>`<label class="v42-check"><input type="checkbox" name="fweekday" value="${v}" ${c.weekdays.includes(v)?'checked':''}><span>${n}</span></label>`).join('')}</div><p class="muted">Weekday buttons are used by “Selected days”. Other controls are ignored unless their matching rule is selected.</p></section>`}
const bm=window.modal;window.modal=function(){let h=bm(),r=state.modal?.mode==='edit'?reminders.find(x=>x.id===state.modal.id):(state.modal?.draft||{});return h.replace(/<label>Repeat<select id="fr">[\s\S]*?<\/select><\/label>/,ui(r))};
const bs=window.saveForm;window.saveForm=function(e){let f=e.currentTarget,ms=state.modal?{...state.modal}:null,el=f.querySelector('#fr427');if(!el)return bs(e);let c={type:el.value,interval:Math.max(1,Number(f.querySelector('#finterval')?.value||1)),weekdays:[...f.querySelectorAll('[name=fweekday]:checked')].map(x=>Number(x.value)).sort(),monthDay:Math.min(31,Math.max(1,Number(f.querySelector('#fmonthday')?.value||1))),afterDays:Math.max(1,Number(f.querySelector('#fafter')?.value||1))};if(c.type==='Selected days'&&!c.weekdays.length){e.preventDefault();alert('Choose at least one weekday for Selected days.');return}let legacy=document.createElement('select');legacy.id='fr';legacy.hidden=true;legacy.innerHTML=`<option selected>${c.type}</option>`;f.appendChild(legacy);bs(e);legacy.remove();let r=ms?.mode==='edit'?reminders.find(x=>x.id===ms.id):reminders[0];if(r){r.recurrenceConfig=engine.normalize({...r,recurrenceConfig:c});r.repeat=label(r.recurrenceConfig);save();render()}};
window.pulseNextDue=(r,completedAt=new Date())=>engine.nextDue(r,completedAt);
window.complete=function(id){let r=reminders.find(x=>x.id===id);if(!r)return;let at=new Date(),n=engine.nextDue(r,at);history.unshift({hid:crypto.randomUUID(),title:r.title,category:r.category,completedAt:at.toISOString(),snapshot:{...r}});reminders=n?reminders.map(x=>x.id===id?{...x,due:n,completedSubtasks:[]}:x):reminders.filter(x=>x.id!==id);save();state.sheet=null;state.detail=null;render();toast(n?`Completed · next ${fmt(n)}`:'Completed')};
const oldMap=window.pulseDbReminder;window.pulseDbReminder=function(r){let x=oldMap(r);x.recurrence_label=r.repeat||'Never';x.recurrence_config=cfg(r);return x};
if(!state.modal)render();
})();
