// Pulse V4.2.10 — advanced recurrence with draft support
(()=>{
const VERSION='4.2.10',types=['Never','Daily','Weekdays','Weekends','Selected days','Every X days','Every X weeks','Monthly','After completion'];
const days=[['Sun',0],['Mon',1],['Tue',2],['Wed',3],['Thu',4],['Fri',5],['Sat',6]];
function cfg(r={}){let c=r.recurrenceConfig||{};return{type:c.type||r.repeat||'Never',interval:Math.max(1,Number(c.interval||1)),weekdays:Array.isArray(c.weekdays)?c.weekdays.map(Number):[],monthDay:Number(c.monthDay||new Date(r.due||Date.now()).getDate()),afterDays:Math.max(1,Number(c.afterDays||1))}}
function label(c){if(c.type==='Selected days')return c.weekdays.length?c.weekdays.map(n=>days.find(x=>x[1]===n)?.[0]).join(', '):'Selected days';if(c.type==='Every X days')return `Every ${c.interval} day${c.interval===1?'':'s'}`;if(c.type==='Every X weeks')return `Every ${c.interval} week${c.interval===1?'':'s'}`;if(c.type==='Monthly')return `Monthly · day ${c.monthDay}`;if(c.type==='After completion')return `${c.afterDays} day${c.afterDays===1?'':'s'} after completion`;return c.type}
function ui(r){let c=cfg(r);return `<section class="v427-recur"><div class="v42-field-title">Repeat</div><select id="fr427">${types.map(x=>`<option ${c.type===x?'selected':''}>${x}</option>`).join('')}</select><div class="v427-options"><label>Interval<input id="finterval" type="number" min="1" max="365" value="${c.interval}"><small>Used by Every X days/weeks</small></label><label>Monthly date<input id="fmonthday" type="number" min="1" max="31" value="${c.monthDay}"></label><label>After completion<input id="fafter" type="number" min="1" max="365" value="${c.afterDays}"><small>Days after you complete it</small></label></div><div class="v427-days">${days.map(([n,v])=>`<label class="v42-check"><input type="checkbox" name="fweekday" value="${v}" ${c.weekdays.includes(v)?'checked':''}><span>${n}</span></label>`).join('')}</div><p class="muted">Weekday buttons are used by “Selected days”. Other controls are ignored unless their matching rule is selected.</p></section>`}
const bm=window.modal;window.modal=function(){let h=bm(),r=state.modal?.mode==='edit'?reminders.find(x=>x.id===state.modal.id):(state.modal?.draft||{});return h.replace(/<label>Repeat<select id="fr">[\s\S]*?<\/select><\/label>/,ui(r))};
const bs=window.saveForm;window.saveForm=function(e){let f=e.currentTarget,ms=state.modal?{...state.modal}:null,el=f.querySelector('#fr427');if(!el)return bs(e);let c={type:el.value,interval:Math.max(1,Number(f.querySelector('#finterval')?.value||1)),weekdays:[...f.querySelectorAll('[name=fweekday]:checked')].map(x=>Number(x.value)).sort(),monthDay:Math.min(31,Math.max(1,Number(f.querySelector('#fmonthday')?.value||1))),afterDays:Math.max(1,Number(f.querySelector('#fafter')?.value||1))};if(c.type==='Selected days'&&!c.weekdays.length){e.preventDefault();alert('Choose at least one weekday for Selected days.');return}let legacy=document.createElement('select');legacy.id='fr';legacy.hidden=true;legacy.innerHTML=`<option selected>${c.type}</option>`;f.appendChild(legacy);bs(e);legacy.remove();let r=ms?.mode==='edit'?reminders.find(x=>x.id===ms.id):reminders[0];if(r){r.recurrenceConfig=c;r.repeat=label(c);save();render()}};
function nextDue(r,completedAt=new Date()){let c=cfg(r),d=new Date(r.due),now=new Date(completedAt),advance=()=>{switch(c.type){case'Daily':d.setDate(d.getDate()+1);break;case'Weekdays':do d.setDate(d.getDate()+1);while([0,6].includes(d.getDay()));break;case'Weekends':do d.setDate(d.getDate()+1);while(![0,6].includes(d.getDay()));break;case'Selected days':do d.setDate(d.getDate()+1);while(!c.weekdays.includes(d.getDay()));break;case'Every X days':d.setDate(d.getDate()+c.interval);break;case'Every X weeks':d.setDate(d.getDate()+7*c.interval);break;case'Monthly':{let h=d.getHours(),m=d.getMinutes(),y=d.getFullYear(),mo=d.getMonth()+1,last=new Date(y,mo+1,0).getDate();d=new Date(y,mo,Math.min(c.monthDay,last),h,m,0,0);break}case'After completion':{d=new Date(now);d.setDate(d.getDate()+c.afterDays);let old=new Date(r.due);d.setHours(old.getHours(),old.getMinutes(),0,0);break}default:return null}return d};if(!advance())return null;if(c.type!=='After completion')while(d<=now)if(!advance())break;return d.toISOString()}
window.pulseNextDue=nextDue;
window.complete=function(id){let r=reminders.find(x=>x.id===id);if(!r)return;let at=new Date(),n=nextDue(r,at);history.unshift({hid:crypto.randomUUID(),title:r.title,category:r.category,completedAt:at.toISOString(),snapshot:{...r}});reminders=n?reminders.map(x=>x.id===id?{...x,due:n,completedSubtasks:[]}:x):reminders.filter(x=>x.id!==id);save();state.sheet=null;state.detail=null;render();toast(n?`Completed · next ${fmt(n)}`:'Completed')};
const oldMap=window.pulseDbReminder;window.pulseDbReminder=function(r){let x=oldMap(r);x.recurrence_label=r.repeat||'Never';x.recurrence_config=cfg(r);return x};
const br=window.render;window.render=function(){br();document.querySelectorAll('.brand small').forEach(x=>x.textContent='V'+VERSION);document.querySelectorAll('.version-box b').forEach(x=>x.textContent='Pulse '+VERSION)};window.PULSE_VERSION=VERSION;render();
})();