// Pulse V4.2.9 — reminder templates stability fix
(()=>{const VERSION='4.2.9';let templates=[];
const safeData=r=>({title:r.title||'',category:r.category||'Personal',type:r.type||'reminder',priority:r.priority||'normal',notes:r.notes||'',subtasks:[...(r.subtasks||[])],alertOffsets:[...(r.alertOffsets||[r.alertOffset??15])],persistent:!!r.persistent,repeat:r.repeat||'Never',recurrenceConfig:r.recurrenceConfig?JSON.parse(JSON.stringify(r.recurrenceConfig)):null,time:r.due?new Date(r.due).toTimeString().slice(0,5):'09:00'});
async function load(){if(!pulseUser){templates=[];return}let {data,error}=await pulseCloud.from('reminder_templates').select('*').eq('user_id',pulseUser.id).order('updated_at',{ascending:false});if(error)throw error;templates=data||[]}
function templateBar(){return `<div class="v428-template-bar"><select id="v428tpl"><option value="">Start from scratch</option>${templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select><button type="button" class="secondary" onclick="pulseApplyTemplate()">Use template</button><button type="button" class="secondary" onclick="pulseOpenTemplates()">Manage</button></div>`}
const bm=window.modal;window.modal=function(){let h=bm();if(!state.modal||state.modal.mode==='templates')return state.modal?.mode==='templates'?manager():h;return h.replace(/(<div class="modal-head">[\s\S]*?<\/div>)/,`$1${templateBar()}`)};
window.pulseApplyTemplate=function(){let id=document.querySelector('#v428tpl')?.value,t=templates.find(x=>x.id===id);if(!t)return;let d=t.template_data||{},f=document.querySelector('.v42-modal');if(!f)return;let set=(q,v)=>{let e=f.querySelector(q);if(e&&v!=null)e.value=v};set('#ft',d.title||'');set('#fc',d.category);set('#fy',d.type);set('#fp',d.priority);set('#fn',d.notes||'');set('#fs',(d.subtasks||[]).join('\n'));let due=f.querySelector('#fd');if(due&&d.time){let day=due.value?.slice(0,10)||new Date().toISOString().slice(0,10);due.value=`${day}T${d.time}`}f.querySelectorAll('[name=v42alert]').forEach(x=>x.checked=(d.alertOffsets||[]).map(Number).includes(Number(x.value)));let per=f.querySelector('#fper');if(per)per.checked=!!d.persistent;let rc=d.recurrenceConfig||{},re=f.querySelector('#fr427');if(re)re.value=rc.type||d.repeat||'Never';set('#finterval',rc.interval||1);set('#fmonthday',rc.monthDay||new Date().getDate());set('#fafter',rc.afterDays||1);f.querySelectorAll('[name=fweekday]').forEach(x=>x.checked=(rc.weekdays||[]).map(Number).includes(Number(x.value)));toast('Template applied')};
window.pulseSaveTemplateFromReminder=async function(id){let r=reminders.find(x=>x.id===id);if(!r||!pulseUser)return;let name=prompt('Template name',r.title);if(!name?.trim())return;let {error}=await pulseCloud.from('reminder_templates').insert({user_id:pulseUser.id,name:name.trim(),template_data:safeData(r)});if(error)return pulseCloudError(error);await load();toast('Template saved')};
window.pulseOpenTemplates=async function(){try{await load();state.modal={mode:'templates'};render()}catch(e){pulseCloudError(e)}};
window.pulseDeleteTemplate=async function(id){if(!confirm('Delete this template?'))return;let {error}=await pulseCloud.from('reminder_templates').delete().eq('id',id).eq('user_id',pulseUser.id);if(error)return pulseCloudError(error);await load();render();toast('Template deleted')};
window.pulseCreateFromTemplate=function(id){state.modal={mode:'create',preset:'reminder'};render();setTimeout(()=>{let s=document.querySelector('#v428tpl');if(s){s.value=id;pulseApplyTemplate()}},0)};
function manager(){return `<div class="modal-backdrop" onclick="state.modal=null;render()"><div class="modal v42-modal" onclick="event.stopPropagation()"><div class="modal-head"><div><p class="section-kicker">REUSE</p><h2>Reminder templates</h2></div><button class="icon-btn" onclick="state.modal=null;render()">×</button></div><p class="muted">Templates are synced to your Pulse account and keep reminder settings without fixing the calendar date.</p><div class="v428-template-manager">${templates.length?templates.map(t=>{let d=t.template_data||{};return `<div class="v428-template-row"><div class="meta"><b>${esc(t.name)}</b><small>${esc(d.category||'Personal')} · ${(d.alertOffsets||[]).length||1} alert${(d.alertOffsets||[]).length===1?'':'s'} · ${esc(d.repeat||'Never')}</small></div><div class="v428-template-actions"><button class="secondary" onclick="pulseCreateFromTemplate('${t.id}')">Use</button><button class="secondary" onclick="pulseDeleteTemplate('${t.id}')">Delete</button></div></div>`}).join(''):'<div class="empty"><b>No templates yet</b><p>Open an existing reminder and choose Save as template.</p></div>'}</div></div></div>`}
const bs=window.sheet;window.sheet=function(){let h=bs();if(!state.sheet||state.sheet.type==='snooze')return h;let id=state.sheet.id;if(!id)return h;return h.replace(`<button onclick="duplicateReminder('${id}')">⧉ Duplicate</button>`,`<button onclick="duplicateReminder('${id}')">⧉ Duplicate</button><button onclick="pulseSaveTemplateFromReminder('${id}')">▣ Save as template</button>`)};
const bd=window.detail;window.detail=function(id){let h=bd(id);if(!id||!h)return h;return h.replace(/(<div class="detail-actions">)/,`$1<button class="secondary" onclick="pulseSaveTemplateFromReminder('${id}')">Save as template</button>`)};
const br=window.render;window.render=function(){br();document.querySelectorAll('.brand small').forEach(x=>x.textContent='V'+VERSION);document.querySelectorAll('.version-box b').forEach(x=>x.textContent='Pulse '+VERSION)};window.PULSE_VERSION=VERSION;
const boot=async()=>{if(pulseUser)try{await load()}catch(e){console.warn('Template load',e)}render()};setTimeout(boot,300);
})();