// Pulse V4.2.11 compatibility — editor + durable alert preferences only
(()=>{
const choices=[['At time',0],['10 min before',10],['15 min before',15],['30 min before',30],['1 hour before',60],['1 day before',1440]];
const label=v=>choices.find(x=>x[1]===Number(v))?.[0]||`${v} min before`;const norm=r=>{if(!Array.isArray(r.alertOffsets))r.alertOffsets=[Number(r.alertOffset??settings.defaultAlert??15)];r.alertOffsets=[...new Set(r.alertOffsets.map(Number).filter(n=>Number.isFinite(n)&&n>=0))].sort((a,b)=>b-a);if(!r.alertOffsets.length)r.alertOffsets=[0];r.alertOffset=r.alertOffsets[0];r.persistent=!!r.persistent;return r};reminders.forEach(norm);const baseSave=window.save;window.save=function(){reminders.forEach(norm);return baseSave()};window.pulseV42AlertOffsets=r=>norm(r).alertOffsets;
const lv=i=>{let x=new Date(i);return new Date(x-x.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function alertsUI(r){norm(r);return `<section class="v42-alert-block"><div class="v42-field-title">Alerts</div><p class="muted">Choose one or more notification times.</p><div class="v42-alert-options">${choices.map(([l,v])=>`<label class="v42-check"><input type="checkbox" name="v42alert" value="${v}" ${r.alertOffsets.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}</div></section><label class="v42-persistent"><input id="fper" type="checkbox" ${r.persistent?'checked':''}><span><b>Persistent reminder</b><small>If still incomplete, repeat every 15 minutes for up to 3 follow-ups.</small></span></label>`}
window.modal=function(){let ed=state.modal.mode==='edit',src=ed?reminders.find(x=>x.id===state.modal.id):(state.modal?.draft||null),p=state.modal.preset||'reminder',r=norm(src?{...src}:{alertOffsets:[Number(settings.defaultAlert??15)],persistent:!!settings.persistentByDefault}),d=src?.due||new Date(Date.now()+3600000).toISOString();return `<div class="modal-backdrop" onclick="state.modal=null;render()"><form class="modal v42-modal" onclick="event.stopPropagation()" onsubmit="saveForm(event)"><div class="modal-head"><div><p class="section-kicker">${ed?'EDIT':'CREATE'}</p><h2>${ed?'Edit reminder':p==='smart'?'New automation':'New reminder'}</h2></div><button type="button" class="icon-btn" onclick="state.modal=null;render()">×</button></div><label>Title<input id="ft" value="${esc(src?.title||'')}" required></label><div class="v42-core-grid"><label>Category<select id="fc">${Object.keys(cats).map(c=>`<option ${src?.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Type<select id="fy"><option value="reminder" ${(src?.type||p)==='reminder'?'selected':''}>Reminder</option><option value="routine" ${(src?.type||p)==='routine'?'selected':''}>Routine</option><option value="smart" ${(src?.type||p)==='smart'?'selected':''}>Automation</option></select></label><label>Date & time<input id="fd" type="datetime-local" value="${lv(d)}" required></label><label>Repeat<select id="fr">${repeats.map(x=>`<option ${src?.repeat===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Priority<select id="fp"><option value="normal">Normal</option><option value="important" ${src?.priority==='important'?'selected':''}>Important</option></select></label></div>${alertsUI(r)}<label>Context / notes<textarea id="fn">${esc(src?.notes||'')}</textarea></label><label>Checklist items<textarea id="fs" placeholder="One item per line">${esc((src?.subtasks||[]).join('\n'))}</textarea></label><div class="modal-actions"><span class="modal-spacer"></span><button type="button" class="secondary" onclick="state.modal=null;render()">Cancel</button><button class="primary">${ed?'Save changes':'Create'}</button></div></form></div>`};
window.saveForm=function(e){e.preventDefault();let f=e.currentTarget,ms={...state.modal},offs=[...f.querySelectorAll('[name=v42alert]:checked')].map(x=>Number(x.value));if(!offs.length)return alert('Choose at least one alert time.');let p={title:f.querySelector('#ft').value.trim(),category:f.querySelector('#fc').value,type:f.querySelector('#fy').value,due:new Date(f.querySelector('#fd').value).toISOString(),repeat:f.querySelector('#fr').value,alertOffsets:[...new Set(offs)].sort((a,b)=>b-a),priority:f.querySelector('#fp').value,notes:f.querySelector('#fn').value.trim(),subtasks:f.querySelector('#fs').value.split('\n').map(x=>x.trim()).filter(Boolean),persistent:!!f.querySelector('#fper')?.checked};p.alertOffset=p.alertOffsets[0];if(ms.mode==='edit')reminders=reminders.map(r=>r.id===ms.id?norm({...r,...p}):r);else reminders.unshift(norm({id:crypto.randomUUID(),...p,enabled:true,completedSubtasks:[],lastResult:p.type==='smart'?'Waiting for first verified check':null}));save();state.modal=null;render();toast(ms.mode==='edit'?'Updated':'Saved')};
const bc=window.card;window.card=function(r){r=norm(r);let h=bc(r);h=h.replace(/<span>🔔 [^<]*<\/span>/,`<span>🔔 ${r.alertOffsets.map(label).join(' + ')}</span>`);if(r.persistent)h=h.replace('</div></div><div class="card-actions">','<span class="persistent-tag">↻ Persistent</span></div></div><div class="card-actions">');return h};
if(typeof pulseLocalSave==='function')pulseLocalSave();
setTimeout(()=>{if(!state.modal)render()},0);
})();
